### ISSUE TITLE
Not support python2.7 python3.5.

### ISSUE THREAD

**Issue by 0h-n0** [nttcslab-sp/kaldiio#2]
Hi. I tested your code with travis CI. As a result, current kaldiio don't support python2.7 and python3.5 due to f-string. However this repo is depened on python2.7 and python3.5 in README.md. [[link](https://github.com/nttcslab-sp/kaldiio/blob/master/README.md#dependencies)]

Here is a result of CI.
* https://travis-ci.org/0h-n0/kaldiio

**Comment by ShigekiKarita** [comment]
Thanks for reporting, we support travis CI.

**Comment by kamo-naoyuki** [comment]
@0h-n0  Now fixed, thanks
