### ISSUE TITLE
in ark.py， below this code has a bug

### ISSUE THREAD

**Issue by Pydataman** [nttcslab-sp/kaldiio#32]
def readtoken(self, ark_read):
        tok = ""
        ch, = ark_read.read(1)
        while ch != ' ':
            tok = tok + ch
            ch, = ark_read.read(1)
        return tok

need str， not int

**Comment by nttcslab-sp-admin** [comment]
kaldiio doesn't have neither `ark.py` nor `readtoken()` and of course, doesn't include such code. What are you talking about?
