### ISSUE TITLE
can i using with WriteHelper as this WriteHelper('scp,ark:file.scp,file.ark') ?

### ISSUE THREAD

**Issue by zh794390558** [nttcslab-sp/kaldiio#38]
Also can WriteHelper save vector ?

**Comment by zh794390558** [comment]
WriteHelper('scp,ark:file.scp,file.ark') this can not work well.

**Comment by zh794390558** [comment]
vector can be saved by WriteHelper

**Comment by nttcslab-sp-admin** [comment]
Didn't it work for you?

```python
from kaldiio import WriteHelper
x = np.random.randn(100)                                                                                                                                                                                   
with kaldiio.WriteHelper('ark,scp:a.ark,a.scp') as f: 
     f['a'] = x
```

**Comment by zh794390558** [comment]
This can work, but I think it can work with `WriteHelper('scp,ark:file.scp,file.ark') `.

**Comment by nttcslab-sp-admin** [comment]
Yeah,  the following should also work, of course.

```python
from kaldiio import WriteHelper
x = np.random.randn(100)                                                                                                                                                                                   
with kaldiio.WriteHelper('scp,ark:file.scp,file.ark') as f: 
     f['a'] = x
```

Doesn't it work at your machine?

**Comment by zh794390558** [comment]
Yes, the file.scp has content of file.ark, but name is file.scp

**Comment by nttcslab-sp-admin** [comment]
That never happens if correctly used. For the evidence, I wrote a test code for it at

 https://github.com/nttcslab-sp/kaldiio/blob/d9d4aae3a5c48b9bd3ec38e0cfe5c29e7899a57f/tests/test_highlevel.py#L58-L69

**Comment by zh794390558** [comment]
ok, thanks.
