### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by danpovey** [nttcslab-sp/kaldiio#41]
Hi,
The tests seem to run fine on a mac but when I tested on Linux I got some failures..
you might want to have a look.

[test.txt](https://github.com/nttcslab-sp/kaldiio/files/3722647/test.txt)

**Comment by nttcslab-sp-admin** [comment]
Thank you for reporting this issue. 

The system default encoding depends on the locale, LC_CTYPE, on Linux environment if you are using Python<3.7, and many people set as C type for fixing the sorting order in the terminal. 
In addition to your previous PR, I modified this program to use utf-8 in any cases as possible, so I think that this issues is almost solved now.
