### ISSUE TITLE
matrix slices differ between KALDI and kaldiio

### ISSUE THREAD

**Issue by kazu-hama** [nttcslab-sp/kaldiio#44]
Hi,
I want to use the kaldiio library to read feats.scp,
but when slices are included in feats.scp file,
KALDI-command and kaldiio-function give different results.

This shell script(test.sh) reproduces the problem:
```bash
#!/bin/bash
matrix-dim /path/to/test.ark:6[3:5]
python3 -c 'import kaldiio; print(kaldiio.load_mat("/path/to/test.ark:6[3:5]").shape)'
```
Execution result:
```
$ test.sh
matrix-dim /path/to/test.ark:6[3:5]
3       20
(2,20)
```

thanks.

**Comment by nttcslab-sp-admin** [comment]
Thanks. I didn't realize it. This is a fatal bug and fixed in the current version.

**Comment by kazu-hama** [comment]
Thanks for your reply, it now work well.
